[tool.ruff]
line-length = 88
fix = true

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"
line-ending = "auto"

[tool.ruff.lint]
extend-ignore = ["E731"]

[tool.ruff.lint.isort]
lines-after-imports = 2



[tool.pyright]

typeCheckingMode = "standard"

pythonVersion = "3.12"
pythonPlatform = "Linux"

# enable subset of "strict"
reportDuplicateImport = true
reportInconsistentConstructor = true
reportInvalidStubStatement = true
reportOverlappingOverload = true
reportPropertyTypeMismatch = true
reportUntypedNamedTuple = true
reportUnusedImport = true
disableBytesTypePromotions = true

# disable subset of "basic"
# reportUntypedFunctionDecorator = false
# reportUntypedClassDecorator = false
# reportArgumentType = false
# reportAssignmentType = false
reportAttributeAccessIssue = false
reportCallIssue = false
# reportGeneralTypeIssues = false
# reportIndexIssue = false
# reportOperatorIssue = false
# reportOptionalCall = false
# reportOptionalIterable = false
# reportOptionalMemberAccess = false
# reportOptionalOperand = false
# reportOptionalSubscript = false
# reportPrivateImportUsage = false
# reportRedeclaration = false
# reportReturnType = false
# reportUnboundVariable = false
# reportMissingModuleSource = false
